SCREEN_WIDTH = 800
SCREEN_HEIGHT = 800

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS


PLAYER_RADIUS = 20 #define he size of the player's ship

PLAYER_TURN_SPEED = 300 #define player turning speed

PLAYER_SPEED = 200 # define player's speed

SHOT_RADIUS = 5 # define shoot

PLAYER_SHOOT_SPEED = 500